# Generated by Django 3.2.13 on 2022-05-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null='True', upload_to='uploads/'),
            preserve_default='True',
        ),
    ]
