# Generated by Django 3.2.13 on 2022-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rating', '0002_auto_20220517_0120'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publicationlike',
            constraint=models.UniqueConstraint(fields=('publication', 'author'),
                                               name='unique_like_per_user_per_publication'),
        ),
    ]
