# Generated by Django 3.2.13 on 2022-05-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_publicationlike_unique_like_per_user_per_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Лайк на комментарии', 'verbose_name_plural': 'Лайки на комментариях'},
        ),
        migrations.AlterModelOptions(
            name='publicationlike',
            options={'verbose_name': 'Лайк на публикации', 'verbose_name_plural': 'Лайки на публикациях'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='publicationlike',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
