# Generated by Django 3.2.13 on 2022-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rating', '0005_auto_20220523_0431'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('comment', 'author'), name='unique_like_per_user_per_comment'),
        ),
    ]
