# Generated by Django 3.2.13 on 2022-05-16 22:20

from django.db import migrations, models

import publications.models


class Migration(migrations.Migration):
    dependencies = [
        ('publications', '0002_alter_publication_post_referred_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_comment',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='post_referred_to',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(default=None, upload_to='attachments/',
                                   validators=[publications.models.validate_photo_or_video], verbose_name='Приложение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('Photo', 'Фото'), ('Video', 'Видео')], default='Photo', max_length=10,
                                   verbose_name='Тип файла'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='place_alias',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название места/заведения'),
        ),
    ]
