# Generated by Django 3.2.13 on 2022-05-24 21:29

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20220523_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [56.078743315545864, 40.53618966182697], 'language': 'ru', 'placeholder': 'Выберите геопозицию на карте', 'zoom': 7}, verbose_name='Расположение'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
