# Generated by Django 3.2.13 on 2022-05-25 11:51

import mapbox_location_field.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('publications', '0006_auto_20220525_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='location',
            field=mapbox_location_field.models.LocationField(
                map_attrs={'center': [37.60024739728942, 55.763870740960954], 'language': 'ru',
                           'placeholder': 'Выберите геопозицию на карте', 'zoom': 7}, verbose_name='Расположение'),
        ),
    ]
