# Generated by Django 3.2.13 on 2022-05-27 15:43

from django.db import migrations, models
import publications.validators


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_alter_publication_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(upload_to='attachments/', validators=[publications.validators.validate_photo_or_video], verbose_name='Приложение'),
        ),
    ]
